// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transaction/accounts/service/interface.go

// package accountssvc is a generated GoMock package.
package accountssvc

import (
	reflect "reflect"

	accounts "github.com/Ruscigno/ticker-signals/internal/transaction/accounts"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountsService is a mock of AccountsService interface.
type MockAccountsService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountsServiceMockRecorder
}

// MockAccountsServiceMockRecorder is the mock recorder for MockAccountsService.
type MockAccountsServiceMockRecorder struct {
	mock *MockAccountsService
}

// NewMockAccountsService creates a new mock instance.
func NewMockAccountsService(ctrl *gomock.Controller) *MockAccountsService {
	mock := &MockAccountsService{ctrl: ctrl}
	mock.recorder = &MockAccountsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountsService) EXPECT() *MockAccountsServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAccountsService) Delete(accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountsServiceMockRecorder) Delete(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountsService)(nil).Delete), accountID)
}

// GetByID mocks base method.
func (m *MockAccountsService) GetByID(accountID int64) (*accounts.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", accountID)
	ret0, _ := ret[0].(*accounts.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountsServiceMockRecorder) GetByID(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountsService)(nil).GetByID), accountID)
}

// Insert mocks base method.
func (m *MockAccountsService) Insert(ac *accounts.Account, serverTime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ac, serverTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAccountsServiceMockRecorder) Insert(ac, serverTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAccountsService)(nil).Insert), ac, serverTime)
}

// Update mocks base method.
func (m *MockAccountsService) Update(ac *accounts.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountsServiceMockRecorder) Update(ac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountsService)(nil).Update), ac)
}
