// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transaction/traderules/repo/interface.go

// package tradeRulesrepo is a generated GoMock package.
package tradeRulesrepo

import (
	reflect "reflect"

	tradeRules "github.com/Ruscigno/ticker-signals/internal/transaction/traderules"
	gomock "github.com/golang/mock/gomock"
)

// MockTradeRulesRepository is a mock of TradeRulesRepository interface.
type MockTradeRulesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTradeRulesRepositoryMockRecorder
}

// MockTradeRulesRepositoryMockRecorder is the mock recorder for MockTradeRulesRepository.
type MockTradeRulesRepositoryMockRecorder struct {
	mock *MockTradeRulesRepository
}

// NewMockTradeRulesRepository creates a new mock instance.
func NewMockTradeRulesRepository(ctrl *gomock.Controller) *MockTradeRulesRepository {
	mock := &MockTradeRulesRepository{ctrl: ctrl}
	mock.recorder = &MockTradeRulesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTradeRulesRepository) EXPECT() *MockTradeRulesRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockTradeRulesRepository) GetAll() ([]*tradeRules.TradeRules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*tradeRules.TradeRules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTradeRulesRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTradeRulesRepository)(nil).GetAll))
}

// GetByAccount mocks base method.
func (m *MockTradeRulesRepository) GetByAccount(accountID int64, ruleType int) ([]*tradeRules.TradeRules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccount", accountID, ruleType)
	ret0, _ := ret[0].([]*tradeRules.TradeRules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccount indicates an expected call of GetByAccount.
func (mr *MockTradeRulesRepositoryMockRecorder) GetByAccount(accountID, ruleType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccount", reflect.TypeOf((*MockTradeRulesRepository)(nil).GetByAccount), accountID, ruleType)
}

// GetBySymbol mocks base method.
func (m *MockTradeRulesRepository) GetBySymbol(accountID int64, symbol string, ruleType int) ([]*tradeRules.TradeRules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbol", accountID, symbol, ruleType)
	ret0, _ := ret[0].([]*tradeRules.TradeRules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbol indicates an expected call of GetBySymbol.
func (mr *MockTradeRulesRepositoryMockRecorder) GetBySymbol(accountID, symbol, ruleType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbol", reflect.TypeOf((*MockTradeRulesRepository)(nil).GetBySymbol), accountID, symbol, ruleType)
}
