---
version: '3'

services:
  ticker-signals:
    image: r.r6o.co/ticker-signals:latest
    container_name: ticker-signals
    ports:
      - 31006:31006
    restart: unless-stopped
    env_file:
      - .env
    networks: 
      - ticker-beats-ntw

networks:
  ticker-beats-ntw:
    driver: bridge