// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tickerbeats/signal/service/interface.go

// package signalsvc is a generated GoMock package.
package signalsvc

import (
	reflect "reflect"

	tickerbeats_v1 "github.com/Ruscigno/ruscigno-gosdk/ticker-beats/v1"
	signal "github.com/Ruscigno/ticker-signals/internal/tickerbeats/signal"
	tradetransaction "github.com/Ruscigno/ticker-signals/internal/transaction/tradetransaction"
	gomock "github.com/golang/mock/gomock"
)

// MockSignalService is a mock of SignalService interface.
type MockSignalService struct {
	ctrl     *gomock.Controller
	recorder *MockSignalServiceMockRecorder
}

// MockSignalServiceMockRecorder is the mock recorder for MockSignalService.
type MockSignalServiceMockRecorder struct {
	mock *MockSignalService
}

// NewMockSignalService creates a new mock instance.
func NewMockSignalService(ctrl *gomock.Controller) *MockSignalService {
	mock := &MockSignalService{ctrl: ctrl}
	mock.recorder = &MockSignalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalService) EXPECT() *MockSignalServiceMockRecorder {
	return m.recorder
}

// CloseDeadPositions mocks base method.
func (m *MockSignalService) CloseDeadPositions(sourceAccountID, destinationAccountID int64, groupID string, minToExpire int32) ([]*tradetransaction.TradeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseDeadPositions", sourceAccountID, destinationAccountID, groupID, minToExpire)
	ret0, _ := ret[0].([]*tradetransaction.TradeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseDeadPositions indicates an expected call of CloseDeadPositions.
func (mr *MockSignalServiceMockRecorder) CloseDeadPositions(sourceAccountID, destinationAccountID, groupID, minToExpire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseDeadPositions", reflect.TypeOf((*MockSignalService)(nil).CloseDeadPositions), sourceAccountID, destinationAccountID, groupID, minToExpire)
}

// ConfirmByExternalID mocks base method.
func (m *MockSignalService) ConfirmByExternalID(destinationAccountID, externalID, tickerBeatsID, positionID int64, status signal.SignalStatusEnum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmByExternalID", destinationAccountID, externalID, tickerBeatsID, positionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmByExternalID indicates an expected call of ConfirmByExternalID.
func (mr *MockSignalServiceMockRecorder) ConfirmByExternalID(destinationAccountID, externalID, tickerBeatsID, positionID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmByExternalID", reflect.TypeOf((*MockSignalService)(nil).ConfirmByExternalID), destinationAccountID, externalID, tickerBeatsID, positionID, status)
}

// CreateTickerBeats mocks base method.
func (m *MockSignalService) CreateTickerBeats(sourceAccountID, destinationAccountID int64, groupID string, minToExpire int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTickerBeats", sourceAccountID, destinationAccountID, groupID, minToExpire)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTickerBeats indicates an expected call of CreateTickerBeats.
func (mr *MockSignalServiceMockRecorder) CreateTickerBeats(sourceAccountID, destinationAccountID, groupID, minToExpire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTickerBeats", reflect.TypeOf((*MockSignalService)(nil).CreateTickerBeats), sourceAccountID, destinationAccountID, groupID, minToExpire)
}

// GetSignalByDestination mocks base method.
func (m *MockSignalService) GetSignalByDestination(accountID int64) ([]*signal.Signal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignalByDestination", accountID)
	ret0, _ := ret[0].([]*signal.Signal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignalByDestination indicates an expected call of GetSignalByDestination.
func (mr *MockSignalServiceMockRecorder) GetSignalByDestination(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignalByDestination", reflect.TypeOf((*MockSignalService)(nil).GetSignalByDestination), accountID)
}

// GetTradeRequesByGroupID mocks base method.
func (m *MockSignalService) GetTradeRequesByGroupID(destinationAccountID int64, groupID string, entry tickerbeats_v1.DealEntry) ([]*tradetransaction.TradeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTradeRequesByGroupID", destinationAccountID, groupID, entry)
	ret0, _ := ret[0].([]*tradetransaction.TradeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradeRequesByGroupID indicates an expected call of GetTradeRequesByGroupID.
func (mr *MockSignalServiceMockRecorder) GetTradeRequesByGroupID(destinationAccountID, groupID, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradeRequesByGroupID", reflect.TypeOf((*MockSignalService)(nil).GetTradeRequesByGroupID), destinationAccountID, groupID, entry)
}

// NeedToCloseAllPositions mocks base method.
func (m *MockSignalService) NeedToCloseAllPositions(accountID int64, groupID string, stop int32) ([]*tradetransaction.TradeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedToCloseAllPositions", accountID, groupID, stop)
	ret0, _ := ret[0].([]*tradetransaction.TradeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeedToCloseAllPositions indicates an expected call of NeedToCloseAllPositions.
func (mr *MockSignalServiceMockRecorder) NeedToCloseAllPositions(accountID, groupID, stop interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedToCloseAllPositions", reflect.TypeOf((*MockSignalService)(nil).NeedToCloseAllPositions), accountID, groupID, stop)
}

// RemoveDuplicatedSignals mocks base method.
func (m *MockSignalService) RemoveDuplicatedSignals(destinationAccountID int64, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDuplicatedSignals", destinationAccountID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDuplicatedSignals indicates an expected call of RemoveDuplicatedSignals.
func (mr *MockSignalServiceMockRecorder) RemoveDuplicatedSignals(destinationAccountID, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDuplicatedSignals", reflect.TypeOf((*MockSignalService)(nil).RemoveDuplicatedSignals), destinationAccountID, groupID)
}

// UpdatePositionIdBeforeClose mocks base method.
func (m *MockSignalService) UpdatePositionIdBeforeClose(sourceAccountID, destinationAccountID int64, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePositionIdBeforeClose", sourceAccountID, destinationAccountID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePositionIdBeforeClose indicates an expected call of UpdatePositionIdBeforeClose.
func (mr *MockSignalServiceMockRecorder) UpdatePositionIdBeforeClose(sourceAccountID, destinationAccountID, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePositionIdBeforeClose", reflect.TypeOf((*MockSignalService)(nil).UpdatePositionIdBeforeClose), sourceAccountID, destinationAccountID, groupID)
}

// UpdateStatus mocks base method.
func (m *MockSignalService) UpdateStatus(sourceAccountID, destinationAccountID int64, status signal.SignalStatusEnum, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", sourceAccountID, destinationAccountID, status, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSignalServiceMockRecorder) UpdateStatus(sourceAccountID, destinationAccountID, status, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSignalService)(nil).UpdateStatus), sourceAccountID, destinationAccountID, status, groupID)
}
